[package]
name = "dougu-essentials-logger"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
log = { workspace = true }
env_logger = { workspace = true }
anyhow = { workspace = true }
