[package]
name = "dougu-essentials-fs"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
log = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = "0.1" 