[package]
name = "dougu-actions"
version = "0.1.0"
edition = "2021"
description = "Actions module for the Dougu project"

[dependencies]
anyhow = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] } 