[package]
name = "dougu-foundation-ui"
version = "0.1.0"
edition = "2024"

[dependencies]
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
colored = "2.1.0"
prettytable-rs = "0.10.0"
textwrap = "0.16.0" 