[package]
name = "dougu"
version = "0.1.0"
edition = "2024"
description = "A multi-command CLI tool with nested command structure for file and Dropbox operations."
license = "Apache-2.0"
authors = ["Takayuki Okazaki <watermint@users.noreply.github.com>"]
repository = "https://github.com/your-org/dougu"
documentation = "https://github.com/your-org/dougu#readme"
homepage = "https://github.com/your-org/dougu"
readme = "../README.md"

[dependencies]
dougu-essentials-logger = "0.1.0"
dougu-essentials-i18n = "0.1.0"
dougu-command-file = "0.1.0"
dougu-command-dropbox = "0.1.0"
clap = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }
