[package]
name = "dougu"
version = "0.1.0"
edition = "2024"

[dependencies]
dougu-essentials-logger = { path = "../dougu-essentials-logger" }
dougu-essentials-i18n = { path = "../dougu-essentials-i18n" }
dougu-command-file = { path = "../dougu-command-file" }
dougu-command-dropbox = { path = "../dougu-command-dropbox" }
clap = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }
