[package]
name = "dougu-foundation-run"
version = "0.1.0"
edition = "2024"

[dependencies]
log = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true } 