name: Build and Test

on:
  push:
    branches: [current]
  pull_request:
    branches: [current]

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build
        id: build
        run: |
          # Build and capture executable information
          BUILD_OUTPUT=$(cargo build --workspace --all-targets --message-format=json)
          EXECUTABLE=$(echo "$BUILD_OUTPUT" | grep -m 1 '"executable"' | cut -d '"' -f 4)
          if [ -z "$EXECUTABLE" ]; then
            echo "No executable found in build output. Aborting." >&2
            exit 1
          fi
          echo "executable=$EXECUTABLE" >> $GITHUB_OUTPUT
          echo "app_name=$(basename $EXECUTABLE)" >> $GITHUB_OUTPUT
      - name: Test
        run: cargo test --workspace --all-targets
      
      # Pack artifact
      - name: Pack artifact
        id: pack_artifact
        shell: bash
        run: |
          # Build the artifact using the build pack command
          mkdir -p target/dist
          PACK_OUTPUT=$(./target/debug/dougu build pack \
            --executable ${{ steps.build.outputs.executable }} \
            --output-dir target/dist)
          
          # Extract information from JSON output
          ARCHIVE_PATH=$(echo "$PACK_OUTPUT" | ./target/debug/dougu obj json query -q '.path')
          ARTIFACT_NAME=$(echo "$PACK_OUTPUT" | ./target/debug/dougu obj json query -q '.name')
          
          # Save information for use in upload step
          echo "archive_path=$ARCHIVE_PATH" >> $GITHUB_OUTPUT
          echo "artifact_name=$ARTIFACT_NAME" >> $GITHUB_OUTPUT
      
      # Upload artifact
      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.pack_artifact.outputs.artifact_name }}
          path: ${{ steps.pack_artifact.outputs.archive_path }} 