name: CI

on:
  push:
    branches: [current]
  pull_request:
    branches: [current]

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          
      - name: Test
        run: cargo test --workspace --all-targets

      - name: Build
        id: build
        shell: bash
        run: |
          # Build the project
          cargo build --workspace --all-targets --message-format=json > build_output.json
          
          # Find executable path using the dougu tool
          # The cargo output is JSON lines format
          EXECUTABLE=$(./target/debug/dougu --ui-skip-appinfo obj extract \
            --format jsonl \
            --raw \
            build_output.json \
            'select(.reason == "compiler-artifact" and .target.kind | contains(["bin"]) and .target.src_path | endswith("/main.rs") and .executable != null) | .executable')
          
          if [ -z "$EXECUTABLE" ]; then
            echo "No executable found matching main.rs. Aborting." >&2
            exit 1
          fi
          
          echo "Found executable: $EXECUTABLE"
          echo "executable=$EXECUTABLE" >> $GITHUB_OUTPUT
          echo "app_name=dougu" >> $GITHUB_OUTPUT
      
      # Pack artifact
      - name: Pack artifact
        id: pack_artifact
        shell: bash
        run: |
          # Build the artifact using the build pack command
          mkdir -p target/dist
          PACK_OUTPUT=$(./target/debug/dougu --ui-skip-appinfo build pack \
            --input-dir target/debug \
            --output-dir target/dist \
            --ui-format jsonl)
          
          # Extract values using proper format (single JSON object)
          ARCHIVE_PATH=$(echo "$PACK_OUTPUT" | ./target/debug/dougu --ui-skip-appinfo obj extract \
            --format json \
            --raw \
            - '.path')
          
          ARTIFACT_NAME=$(echo "$PACK_OUTPUT" | ./target/debug/dougu --ui-skip-appinfo obj extract \
            --format json \
            --raw \
            - '.name')
          
          echo "ARCHIVE_PATH: $ARCHIVE_PATH"
          echo "ARTIFACT_NAME: $ARTIFACT_NAME"
          
          echo "archive_path=$ARCHIVE_PATH" >> $GITHUB_OUTPUT
          echo "artifact_name=$ARTIFACT_NAME" >> $GITHUB_OUTPUT
      
      # Upload artifact
      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.pack_artifact.outputs.artifact_name }}
          path: ${{ steps.pack_artifact.outputs.archive_path }} 